Перламутровые пуговицы
htmlacademy-javascript/1967081-keksobooking-25 pull request #13
Opened 2022-04-03 14:26 UTC by Cr4zyGleb

2022-04-03 19:15 UTC, frontstall requested changes

2022-04-03 19:15 UTC, frontstall commented on js/map.js
> +const map = initializateFirstLayer();
в проекте нет такой абстракции, как слой. Есть карта и есть точки.

Не плоди сущностей без необходимости :)

2022-04-03 19:15 UTC, frontstall commented on js/map.js
> +let allAnnouncements = [];
глобальные переменные – зло. Карта, точки, объявления должны быть внутри функций. В модулях только объявления функций и констант, импорты и экспорты. Вызовы функций только в точке входа.

2022-04-03 19:15 UTC, frontstall commented on js/map.js
> +  const announcements = [...allAnnouncements];
прими эту внешнюю переменную в качестве аргумента, чтобы функция не зависела от окружения, в котором вызывается, а только от своих аргументов.

2022-04-03 19:15 UTC, frontstall commented on js/map.js
> +// const onChangeFiltersDebounce = () => {
лишний код выпиливаем, есть критерий про мусор

2022-04-03 19:15 UTC, frontstall commented on js/map.js
> +  createIcon(true);
сделай просто две разные функции, одна может внутри себя вызывать другую, если нужно. В случае, если нужно будет сделать ещё какой-то вид иконки, придётся переписать не просто функцию, но и все места, где она вызывается. Вот как раз про твой случай: https://ru.hexlet.io/blog/posts/sovershennyy-kod-plohie-i-horoshie-praktiki-pri-proektirovanii-parametrov-funktsiy

2022-04-03 19:15 UTC, frontstall commented on js/map.js
> +  return L.map('map-canvas')
функция инициализации не может ничего возвращать, это процедура или команда, т.е. она что-то делает, какой-то побочный эффект. Если функция что-то возвращает, то ей нужно другое название, соответствующее тому, что функция делает.

2022-04-03 19:15 UTC, frontstall commented on js/map.js
>  function setAdress(lat, lng) {
не set, а get. 

set это команда, get – это запрос.

2022-04-03 19:15 UTC, frontstall commented on js/map.js
> +// function createPoints(map, announcements) {
лишний код отрываем без сожалений

2022-04-03 19:15 UTC, frontstall commented on js/selection.js
> +  if (!(offer.type === housingType.value)) {
!==

2022-04-03 19:15 UTC, frontstall commented on js/selection.js
> +    if (!(offer.price >= priceMin && offer.price <= priceMax)) {
сложно, давай избавимся от отрицания

2022-04-03 19:15 UTC, frontstall commented on js/selection.js
> +// function findFeaturesInCheckedList(feature) {
мусор

2022-04-03 19:15 UTC, frontstall commented on js/selection.js
> +  for (let i = 0; i < housingFeaturesChecked.length; i++) {
выглядит как housingFeaturesChecked.map

2022-04-03 19:15 UTC, frontstall commented on js/selection.js
> +  const isNotFound = checkedFeaturesInputs.some((elem)=> offer.features.indexOf(elem) < 0);
indexOf используется для поиска индекса. Для определения того, есть ли определённый элемент в массиве, используй includes. С – семантика!

2022-04-03 19:15 UTC, frontstall commented on js/selection.js
> +function checkfilters(announcement) {
camelCase, критерий

2022-04-04 08:08 UTC, Cr4zyGleb commented on js/map.js
> +const map = initializateFirstLayer();
+

2022-04-04 08:08 UTC, Cr4zyGleb commented on js/map.js
> +let allAnnouncements = [];
+

2022-04-04 08:11 UTC, Cr4zyGleb commented on js/map.js
> +  const announcements = [...allAnnouncements];
Тут проблема в том, что фильтры которые мы делаем, не должны запрашивать данные повторно с сервера. То есть нужно где-то хранить список объявлений полученных с сервера. Я не нашёл конечно прямого указания что на не нужно получать данные с сервера при фильтрации, но в дискорде так сказали. Правда не наставник, а ученик.

2022-04-04 08:13 UTC, Cr4zyGleb commented on js/map.js
> +// const onChangeFiltersDebounce = () => {
+

2022-04-04 08:14 UTC, Cr4zyGleb commented on js/selection.js
> +// function findFeaturesInCheckedList(feature) {
+

2022-04-04 08:16 UTC, Cr4zyGleb commented on js/selection.js
> +function checkfilters(announcement) {
+

2022-04-04 08:19 UTC, Cr4zyGleb commented on js/selection.js
> +  const isNotFound = checkedFeaturesInputs.some((elem)=> offer.features.indexOf(elem) < 0);
+

2022-04-04 08:20 UTC, Cr4zyGleb commented on js/selection.js
> +    if (!(offer.price >= priceMin && offer.price <= priceMax)) {
+

2022-04-04 08:24 UTC, Cr4zyGleb commented on js/map.js
> +  createIcon(true);
+

2022-04-04 08:25 UTC, Cr4zyGleb commented on js/selection.js
> +  for (let i = 0; i < housingFeaturesChecked.length; i++) {
Не понял комментария.

2022-04-04 08:27 UTC, Cr4zyGleb commented on js/map.js
> +  return L.map('map-canvas')
+

2022-04-04 08:27 UTC, Cr4zyGleb commented on js/map.js
>  function setAdress(lat, lng) {
+

2022-04-04 08:28 UTC, Cr4zyGleb commented on js/map.js
> +// function createPoints(map, announcements) {
+

2022-04-04 08:29 UTC, Cr4zyGleb commented on js/selection.js
> +  if (!(offer.type === housingType.value)) {
+

2022-04-04 08:37 UTC, frontstall commented on js/map.js
> +  const announcements = [...allAnnouncements];
По тому, как должно работать приложение, есть исчерпывающее ТЗ.

Если хочешь один раз запросить - тоже не проблема сделать это без глобальных переменных.

2022-04-04 08:37 UTC, frontstall commented on js/selection.js
> +  for (let i = 0; i < housingFeaturesChecked.length; i++) {
Вместо цикла используй map.

2022-04-04 18:02 UTC, Cr4zyGleb commented on js/map.js
> +  const announcements = [...allAnnouncements];
Не разобрался как передать параметр в CallBack. Если бы была просто функция, то ок. А у меня Bounce(callback)
И когда Bounce вызывается там он должен получить Массив Объявлений.

2022-04-04 18:15 UTC, Cr4zyGleb commented on js/selection.js
> +  for (let i = 0; i < housingFeaturesChecked.length; i++) {
Это не массив, а набор полученный через QuerySelectorAll
const housingFeaturesChecked = housingFeaturesFieldset.querySelectorAll('.map__checkbox:checked');
Пишет у него не работает Map

2022-04-06 20:17 UTC, merged