main.js
htmlacademy-javascript/1967081-keksobooking-25 pull request #3
Opened 2022-02-19 12:10 UTC by Cr4zyGleb

2022-02-19 17:03 UTC, frontstall requested changes

2022-02-19 17:03 UTC, frontstall commented on js/main.js
> +    if (min < 0) {
линтер ругается, надо исправить все его замечания. У тебя не установлены инструменты, которое это отслеживают. В терминале, находясь в корне проекта, выполни команду `npm install`.

2022-02-19 17:03 UTC, frontstall commented on js/main.js
> +function randomIntegerMinMax(min, max) {
Название функции всегда начинается с глагола, про это есть критерий. Это важное соглашение для написания хорошо читаемого кода.

2022-02-19 17:03 UTC, frontstall commented on js/main.js
> +function randomFloatMinMax(min, max) {
с глагола
посмотри в описании к домашке: эта функция должна позволять указывать нужную точность после запятой

2022-02-19 17:03 UTC, frontstall commented on js/main.js
> +    return Math.round(result);
первое и последнее числа из диапазона будут встречаться в два раза реже, чем остальные. Это не рандом :)

посмотри на mdn или learn.javascript.ru, как получить случайное число из интервала.

2022-02-20 16:10 UTC, frontstall requested changes

2022-02-20 16:10 UTC, frontstall commented on .eslintrc.js
> +module.exports = {
Этот файл не нужен, в корне проекта уже есть конфиг линтера

2022-02-20 16:10 UTC, frontstall commented on js/main.js
> +/* eslint-disable require-jsdoc */
лишнее

2022-02-20 16:10 UTC, frontstall commented on js/main.js
> +  }
если аргументы невалидные, дальнейшая работа функции не имеет смысла. Обычно в этом случае выбрасывается исключение. Для простоты на этом этапе будем исходить из того, что аргументы всегда неотрицательные. Убираем эти блоки

2022-02-20 16:10 UTC, frontstall commented on js/main.js
> +  }
аналогично

2022-02-20 16:10 UTC, frontstall commented on js/main.js
> +function getRandomFloatMinMax(min, max, decimalPlaces) {
decimalPlaces - не очень хорошее именование. Во множественном числе принято называть коллекции элементов, тут же число знаков после запятой. digitsNumber - ок

2022-02-20 16:10 UTC, frontstall commented on js/main.js
> +  if (typeof (decimalPlaces) == 'undefined') {
для параметров по умолчанию существует специальный синтаксис. Давай исходить из того, что все аргументы переданы.

2022-02-20 16:10 UTC, frontstall commented on js/main.js
> +  let result = min + Math.random() * (max + 1 - min);
это же ещё не результат. Именование очень важно.

2022-02-20 16:10 UTC, frontstall commented on package.json
> +    "eslint": "^8.9.0",
еслинт уже установлен

2022-02-20 16:10 UTC, frontstall commented on package.json
> +    "eslint-config-google": "^0.14.0",
используем дефолтный конфиг проекта

2022-02-20 21:49 UTC, closed without merging

2022-02-20 21:49 UTC, Cr4zyGleb commented
Накосячил с удалением, изменением лишних файлов