task4:
htmlacademy-javascript/1967081-keksobooking-25 pull request #5
Opened 2022-02-27 21:36 UTC by Cr4zyGleb

2022-03-01 16:09 UTC, frontstall requested changes

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +  return +result.toFixed(digits);
Явное лучше неявного, и поэтому предпочтительно использовать Number() для приведения к числу вместо плюса

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +const types = ['palace', 'flat', 'house', 'bungalow', 'hotel'];
Это список констант, поэтому в UPPER_CASE

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +function getRandomFeatures(){
пробел между круглыми скобками и фигурными, пробелы вокруг операторов. Надо что-то сделать с форматированием в редакторе, чтобы не править это руками.

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +  for (let i = 1; i<=7; i++){
неплохо! но всё же длина определяется не случайным выбором из пяти вариантов, (кстати, а почему цикл ходит до 7?), т.е. нормальным распределением (когда 1 встречается так же часто, как и 5) тут не пахнет.

алгоритм такой: сначала определяем количество фич N, выбирая случайное число от 1 до 5. Затем перемешиваем копию (чтобы не перемешать оригинальный массив) массива и берём от него N первых элементов. Для перемешивания массива можно использовать алгоритм [Фишера-Йетса](https://ru.wikipedia.org/wiki/%D0%A2%D0%B0%D1%81%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D0%A4%D0%B8%D1%88%D0%B5%D1%80%D0%B0_%E2%80%94_%D0%99%D0%B5%D1%82%D1%81%D0%B0). Можно попробовать реализовать самостоятельно по описанию, можно подглядеть в [библиотеке lodash](https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L9816)

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +function getPhotos(a, b){
неясно, что такое a и b. Нужна функция генерации одной фотки, эту функцию потом можно запустить сколько нужно раз.

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +function createObjects(amount=10) {
название функции должно объяснять, что функция делает. Создавать объекты - слишком абстрактное понятие

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +    //author
комменты в стиле капитана очевидность не упрощают код) комменты есть смысл писать там, где непонятно, что происходит в коде по самому коду, и ничего поделать с этим нельзя. Тут всё достаточно очевидно.

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +    newAnnouncement.author.avatar = `img/avatars/user${number}.png`;
хочется видеть функцию получения урла аватарки. Функции нужны, чтобы скрыть реализацию и при необходимости поменять эту реализацию без изменения внешнего кода.

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +    newAnnouncement.location.lat = getRandomPositiveFloat(35.65000,35.70000,5);
здесь и далее: неочевидные константы нужно выносить в собственно константы, избегая магических чисел

2022-03-01 16:09 UTC, frontstall commented on js/main.js
> +    newAnnouncement.type = types[getRandomPositiveInteger (0, 4)];
хочется видеть функцию получения случайного элемента массива

2022-03-03 20:00 UTC, Cr4zyGleb commented on js/main.js
> +  return +result.toFixed(digits);
+

2022-03-03 20:00 UTC, Cr4zyGleb commented on js/main.js
> +const types = ['palace', 'flat', 'house', 'bungalow', 'hotel'];
+

2022-03-03 20:00 UTC, Cr4zyGleb commented on js/main.js
> +function getRandomFeatures(){
+

2022-03-03 20:01 UTC, Cr4zyGleb commented on js/main.js
> +function getPhotos(a, b){
+

2022-03-03 20:01 UTC, Cr4zyGleb commented on js/main.js
> +function createObjects(amount=10) {
+

2022-03-03 20:01 UTC, Cr4zyGleb commented on js/main.js
> +    //author
+

2022-03-03 20:01 UTC, Cr4zyGleb commented on js/main.js
> +    newAnnouncement.author.avatar = `img/avatars/user${number}.png`;
+

2022-03-03 20:01 UTC, Cr4zyGleb commented on js/main.js
> +    newAnnouncement.location.lat = getRandomPositiveFloat(35.65000,35.70000,5);
+

2022-03-03 20:08 UTC, Cr4zyGleb commented on js/main.js
> +    newAnnouncement.type = types[getRandomPositiveInteger (0, 4)];
+

2022-03-03 22:03 UTC, Cr4zyGleb commented on js/main.js
> +  for (let i = 1; i<=7; i++){
+

2022-03-04 06:46 UTC, merged